Repository opensafely-core/opencodelists, pull requests merged in 2025-05, with the labels that each got.

#2488 Address unnecessary monkeypatching
  opencodelists/management/commands/setup_local_dev_databases.py
  opencodelists/tests/management/commands/test_setup_local_dev_databases.py
  pyproject.toml
Labels: bug

#2520 Add `just build-dbs-for-local-development` to DEVELOPERS.md
  DEVELOPERS.md
Labels: documentation

#2580 Update JS dependencies
  package-lock.json
  package.json
Labels: dependencies, javascript
